INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (1, 'Япония', 'Антон Борисов', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (2, 'Италия', 'Геворг Гезалян', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (3, 'Аргентина', 'Алексей Дупляков', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (4, 'Сербия', 'Максим Крюков', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (5, 'Хорватия', 'Олег Кудрявцев', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (7, 'Германия', 'Антон Пиковский', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (8, 'Россия', 'Дмитрий Самойлов', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (9, 'Англия', 'Вадим Швецов', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (10, 'Исландия', 'Александр Шевченко', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (6, 'Уругвай', 'Даниил Кузьмин', '??', 2018);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (23, 'Leeds United', 'Никита Бахуров', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (24, 'Newcastle United', 'Антон Борисов', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (25, 'Stoke City', 'Станислав Борисов', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (26, 'Bolton Wanderers', 'Геворг Гезалян', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (27, 'Tottenham Hotspur', 'Олег Кудрявцев', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (28, 'Sunderland', 'Даниил Кузьмин', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (29, 'Aston Villa', 'Антон Пиковский', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (30, 'Liverpool', 'Дмитрий Самойлов', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (31, 'Manchester United', 'Максим Крюков', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (32, 'Bournemouth', 'Вадим Швецов', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (33, 'Leicester City', 'Александр Шевченко', null, 2017);
INSERT INTO voroshila.public.teams(team_id, team_name, full_name, team_emoji, year) VALUES (34, 'West Ham United', 'Александр Фастов', null, 2017);
